version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
clone_depth: 1
init:
- cmd: git config --global core.autocrlf true
install:
- cmd: >-
    set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%

    pip3 install -r requirements.txt

    pip3 install pyinstaller
build_script:
- cmd: >-
    set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%

    set CI_HASH=%APPVEYOR_REPO_COMMIT:~0,7%

    set PYTHONOPTIMIZE=1

    cd packaging\windows

    pyinstaller --log-level=INFO --distpath=results\dist --workpath=results\build --clean --noconfirm --onefile --noupx --name=wloc --version-file=assets\version.txt --manifest=assets\wloc.manifest --icon=assets\wloc.ico ..\..\wloc\app\run.py

    "%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe" inno\wloc.iss
test: off
artifacts:
- path: packaging\windows\results\snapshot_*.exe
  name: innosetup
deploy: off
